### ISSUE TITLE
Issue with removing hover event on phone

### ISSUE THREAD

**Issue by JustBoyke** [lucasnijssen/Cine-Plus#1]
When you click on a movie the hover will be blocked on PC, but on mobile devices (without mouse pointer) it seems like this won`t work. Needs a fix ASAP.

**Comment by vdtuinj** [comment]
Using the CSS @media and any-hover this could be blocked on (mobile) devices not supporting hover.

**Comment by JustBoyke** [comment]
> Using the CSS media and any-hover this could be blocked on (mobile) devices not supporting hover.

Checked this, it should be possible, only the hover removing is not working in the current version. This has prob to do with mobile devives not realy hovering over it but just selecting it so the JS will not see it as a hover event.
